routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Models\Article;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|Здесь вы можете зарегистрировать веб-маршруты для своего приложения.
Эти маршруты загружаются RouteServiceProvider внутри группы,
которая содержит группу middleware «web».
Теперь создайте что-нибудь отличное!
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('index');

//Route::get('/article', [App\Http\Controllers\ArticleController::class, 'index']);

//Route::get('/category', [App\Http\Controllers\CategoryController::class, 'index'])->name('category');

Route::get('/contact', [App\Http\Controllers\ContactController::class, 'index']);

Route::get('/cart', [App\Http\Controllers\CartController::class, 'index']);

//Route::get('/test/{user}', [App\Http\Controllers\TestController::class, 'index']);
Route::get('/test', [App\Http\Controllers\TestController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

$request = request();
$url = $request->path();

// if (Product::where('slug', $url)->first()) {
//     Route::get('/{slug}', [App\Http\Controllers\SingleProductController::class, 'index']);
// }

// if (Category::where('slug', $url)->first()) {
//     Route::get('/{slug}', [App\Http\Controllers\CategoryController::class, 'index']);
// }

// if (Article::where('slug', $url)->first()) {
//     Route::get('/{slug}', [App\Http\Controllers\ArticleController::class, 'index']);
// }




/*
$slugs = DB::table('products')->get('slug');

foreach ($slugs as $slug) {

    Route::get('/{' . $slug->slug . '}', [App\Http\Controllers\SingleProductController::class, 'index'])->name('single-product');

}
"

$slugs = DB::table('categories')->get('slug');
foreach ($slugs as $slug) {
    Route::get('/{slug}', [App\Http\Controllers\CategoryController::class, 'index'])->name('category');
}
*/
//------------------------------------------ADMIN----------------------------
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {

    
    Route::get('/user/ajax', [ App\Http\Controllers\Admin\UserController::class,'ajax' ]);
    Route::resource('user', App\Http\Controllers\Admin\UserController::class);
   

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     * Атрибуты, которые могут быть назначены массово.
     *
     * @var array
     */
    protected $fillable = [  //разрешаем Классу менять эти поля в базе данных
        'name',
        'email',
        'password',
        'phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     * Атрибуты, которые должны быть скрыты для массивов.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     * Атрибуты, которые следует приводить к собственным типам.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


        $users = User::query();
        $id = $request->get('id');
        $email = $request->get('email');
        $paginate = $request->get('paginate',20);
        if ($id) {
            $users->where('id', $id);
        }
        if ($email) {
            $users->where('email', 'like', '%' . $email . '%');
        }


        return view('admin.users.index', [
            'users' => $users->orderBy('phone')->paginate($paginate ),
            'id' => $id,
            'email' => $email,
        ]);
    }
    public function ajax(Request $request)
    {
        $users = User::query();
        $id = $request->get('id');
        $email = $request->get('email');
        $paginate = $request->get('paginate',20);
        if ($id) {
            $users->where('id', $id);
        }
        if ($email) {
            $users->where('email', 'like', '%' . $email . '%');
        }


        return response()->json($users->orderBy('phone')->paginate($paginate ));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User();

        $request->validate([
            'email'=>'email|required|max:200',
        ]);
        
        $user->fill(  
            $request->only(['name',        'email',        'phone'])
        );
        $user->save();

        return redirect(route('user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.users.edit');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,User $user)
    {


       
        return view('admin.users.edit',[
            'user'=> $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

        $request->validate([
            'email'=>'email|required|max:200',
        ]);
        
        $user->fill(  
            $request->only(['name',        'email',        'phone'])
        );
        $user->save();

        return redirect(route('admin.user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( User $user)
    {

        $user->delete();

        return redirect(route('admin.user.index'));
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form action="{{route('admin.user.update',['user'=>$user])}}" method="POST">
            <input type="hidden" name="_method" value="put" />

                @csrf

                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" autofocus>

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">Name</label>

                    <div class="col-md-6">
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required  autofocus>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">phone</label>

                    <div class="col-md-6">
                        <input   type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $user->phone }}" required  autofocus>

                        @error('phone')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <input type="submit" value="save" />
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <form id="search_form">
                    <input id="id" name="id" type="text" placeholder="id" value="{{request()->get('id')}}" />
                    <input id="email" name="email" type="text" placeholder="email" value="{{request()->get('email')}}" />
                    <select name="paginate">
                        <option> Записей на странице {{request()->get('paginate')}} </option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>

                    </select>
                    <input type="submit">
                </form>

                @if($users->count()>0)
                <table border="1">
                    @foreach($users as $user)
                    <tr>
                        <td><a href="{{ route('admin.user.edit',['user'=>$user->id]) }}">{{ $user->name }}</a></td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>

                            <form method="POST" action="{{ route('admin.user.destroy',['user'=>$user->id]) }}">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">

                                <input type="submit" value="delete {{ $user->name }}" />

                            </form>

                        </td>
                    </tr>
                    @endforeach
                </table>
                {{$users->links()}}
                @else
                no records
                @endif
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script>
    $('#search_form').bind('submit', function(e) {
        e.preventDefault();
        
        var id  = $('#id').val();
        var email  = $('#email').val();
        $('table tr').remove();
        $.ajax({
            url: "http://127.0.0.1:8000/admin/user/ajax",
            data: {id :id,email:email }
        }).done(function(data) {
            //console.log(data);
            $(data.data).each(function(i, item) {
                // console.log(i, item);

                $('table').append('<tr>' 

                    +'<td>' + item.name + '</td>' +
                    '<td>' + item.email + '</td>' +
                    '<td>' + item.phone + '</td>' +
                    '</tr>');
            });
        });

    });
</script>
@endsection

resources/views/admin/users/one.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
              
                        <h2>{{ $user->name }}</h2>
                        <h2>{{ $user->email }}</h2>
                        <h2>{{ $user->phone }}</h2>
                 
            </div>
        </div>
    </div>
</div>
@endsection